apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace-mc-infra.yaml
- namespace-minecraft.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- deployment.yaml
- service.yaml
- gateway.yaml
- virtualservice.yaml
- destinationrule.yaml
