apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-backend
  namespace: mc-infra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: minecraft-backend
    app.kubernetes.io/part-of: minecraft-platform
